trigger:
  - starter-no-infra

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: dotnet publish -o $(Build.ArtifactStagingDirectory)/app
  displayName: 'Publish app'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'sc-appservice-dotnet'
    appType: 'webAppLinux'
    appName: 'wa-dotnet-microsoft'
    package: '$(Build.ArtifactStagingDirectory)/app'